version: "3.9"

services:
  api:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - MONGODB_URL=${MONGODB_URL}
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
